name: Generate Pac-Man Contribution Animation

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    paths:
      - 'scripts/build_pacman_svg.js'
      - '.github/workflows/pacman-contrib.yml'

jobs:
  generate-animation:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Generate Pac-Man SVG
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd scripts
          node build_pacman_svg.js
      
      - name: Check for changes
        id: git-check
        run: |
          if git diff --exit-code assets/pacman-contrib.svg >/dev/null 2>&1; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi
      
      - name: Commit and push if changed
        if: steps.git-check.outputs.changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Pac-Man Bot"
          git add assets/pacman-contrib.svg
          git commit -m "Update Pac-Man contribution animation [$(date +'%Y-%m-%d %H:%M UTC')]"
          git push
      
      - name: Output result
        run: |
          if [ "${{ steps.git-check.outputs.changed }}" = "true" ]; then
            echo "Pac-Man animation updated with latest contributions!"
          else
            echo "No changes in contributions, animation unchanged."
          fi
